apiVersion: v1
kind: Pod
metadata: 
 name: results-app-pod
 labels:
   name: results-app-pod
   app: demo-voting-app
spec:
  containers:
  - name: results-app
    image: violinist999/result:v1
    ports:
    - containerPort: 80
    