apiVersion: v1
kind: Service
metadata:
 name: results-service
 namespace: voting-app
 labels:
   name: results-service
   app: demo-voting-app
spec:
  type: NodePort
  ports:
   - port: 80
     targetPort: 80
     nodePort: 30002
  selector:
    name: results-app-pod
    app: demo-voting-app
   